version: '3.8'

services:
  redis:
    image: arm64v8/redis:latest
    container_name: my-redis
    ports:
      - "6378:6379"
    networks:
      - redis_net

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  redis_net:
    external: false

volumes:
  mongo-data:
